# Generated by Django 5.1 on 2024-08-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='acces_token',
            new_name='access_token',
        ),
    ]
